core: jni: Don't error out on unused function
frameworks/base/core/jni/android_hardware_Camera.cpp:523:13: error: unused function 'android_hardware_Camera_stopLongshot' [-Werror,-Wunused-function]
static void android_hardware_Camera_stopLongshot(JNIEnv *env, jobject thiz)
            ^
1 error generated.

(Due to f1a5e06e70e4a427853321f33ff18bab2c75b38f)

Change-Id: I54dd84561899421d99123b4712c62c00f1979474